### ISSUE TITLE
Allow updating Chrome to the latest version

### ISSUE THREAD

**Issue by OrBin** [cmprescott/ansible-role-chrome#10]
[Here](https://github.com/cmprescott/ansible-role-chrome/blob/master/tasks/setup-apt.yml#L17), replacing `state: present` with `state: latest` should update to the latest version, which might be desired in some cases.

Could you please allow doing this using a role variable?

**Comment by cmprescott** [comment]
That makes sense assuming you mean using defaults when you say `role variable`. If you want to create a PR I'll review and merge in.
