### ISSUE TITLE
apt | update cache task fails with "NoneType is not iterable"

### ISSUE THREAD

**Issue by fanatique** [cmprescott/ansible-role-chrome#5]
Hello Chris,
first of all thank you very much for writing this Ansible role. I've been using it successfully for installing Chrome on a Debian Jessy machine and it works quite nicely.

The only thing which was a bit irritating is that from time to time the `apt | update cache` task failed with "NoneType is not iterable".

I've been able to work around this problem by simple setting `update_cache=yes` but since this is a bit hacky, I didn't want to send this "solution" as a PR.

Maybe you could have a look at this and come across a solution that is a bit more robust then mine.

Thanks again and keep up the good work!

Cheers,
Alex

**Comment by adduc** [comment]
What version of the role are you using? There was a fix in master (commit 261fb04) that may resolve your issue. Could you give it a shot and report back?

**Comment by aisch** [comment]
@adduc i ran into same problem. switching to install from git master (i was installing from latest release `0.2.1`) fixed it.

**Comment by adduc** [comment]
@cmprescott could you tag a new release?

**Comment by cmprescott** [comment]
Done. Sorry took me so long to respond.
